all:
	$(CC) -Wall -Wextra -Werror -std=c11 session_state_test.c -o session_state_test
	./session_state_test
	$(CC) -Wall -Wextra -Werror -std=c11 discontinuity_test.c -o discontinuity_test
	./discontinuity_test
